version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Add assignees
    assignees:
      - "woolinsilver-sknups"
      - "henriquedelgado"
      - "wgriffiths"