services:
  flex:
    volumes:
      - $GOOGLE_APPLICATION_CREDENTIALS:/gcloud.json:ro
    environment:
      GCLOUD_PROJECT: drm-apps-01-43b0
      GOOGLE_APPLICATION_CREDENTIALS: /gcloud.json
      DRM_SERVER: https://drm-service-dev.sknups.com
      GOOGLE_AUTH_TOKEN: $GOOGLE_AUTH_TOKEN
      ENVIRONMENT: dev
