name: Pull request

on:
  pull_request

env:
  GOOGLE_PROJECT: dev-drm-admin-5548
  IMAGE: flex

concurrency: ci-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |-
        docker build --tag "eu.gcr.io/$GOOGLE_PROJECT/$IMAGE:$GITHUB_SHA" .
