---
name: Push to branch

'on':
  push:
    branches:
      - '*'
      - '!main'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches:
      - 'main'

jobs:

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit